language: node_js
sudo: required
node_js:
  - 10
cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - yarn global add hexo-cli

install:
  - yarn install

# ~/build/chenyifaerfans/chenyifaerfans
script:
  - chmod +x ./build.sh && ./build.sh

deploy:
  provider: pages
  email: kjxbyz@163.com
  name: kjxbyz
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: ../blog

#after_script:
#  - git config --global user.name "kjxbyz"
#  - git config --global user.email "kjxbyz@163.com"
#  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
#  - sed -i "s/github_token/${GITHUB_TOKEN}/g" ./_config.yml
#  - sed -i "s/gitee_token/${GITEE_TOKEN}/g" ./_config.yml
#  - cat ./_config.yml
#  - hexo deploy
